#测试环境配置文件
server:
  port: 7080
  session-timeout: 60
  tomcat:
      uri-encoding: UTF-8
spring:
    # 数据源配置
    datasource:
        url: jdbc:mysql://139.159.198.250:3306/qht?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false # 内网服务器
        username: root
        password: qht123456
        connection-timeout: 120000
        driver-class-name: com.mysql.jdbc.Driver
        sql-script-encoding: utf-8
        initialSize: 5 #初始化大小
        minIdle: 5 #最小
        maxActive: 100 #最大
        maxWait: 60000 #配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis : 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true #打开PSCache
        maxPoolPreparedStatementPerConnectionSize: 20 #指定每个连接上PSCache的大小
    http:
        multipart:
          max-file-size: 100Mb      # Max file size
          max-request-size: 100Mb   # Max request size
    redis:
      database: 0
      host: 139.159.198.250
      port: 6379
      password: qht123456
      timeout: 0
      max-active: 8
      max-wait: -1
      max-idle: 8
      pool.min-idle: 0
    session:
      store-type: redis
securityconfig:
  logoutsuccssurl: /login_out
  permitall: /*/app/**,/doc.html,/user/web/getCode,/user/web/updateuserpassword,/user/web/updatepassword,/*.ico,/,/*.html,/images/**,/checkcode,/lib/**,/fonts/**,/js/**,/monitoring/findTestMacById,/testmacdata/searchTestmacData,/css/**"
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin

#OSS
#支付
alipay:
  appID: 2018111962241430
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCHfopAG8cp9daTnnZQJiXhrg5gdt8jk/rruvVV31+H0ro/f/5nRp9hjWR13kEJH9cmyW5JhMHVfDSWpJ/I6s3tmKGQEY2azPGeRnjCMjg/t7bXC8pSM4sPbRggXFbRobMsV9HBqQvQhtNRdlQsIAqChoji1tXuG5Pfm6GIkq2pP+LTnNUjVC0y1GeBaBJ1cFZoINmiJAgLMC6Tpb1sDGCMZ3NYdwMq8MfD/1Nwp3s2hqQBW0Ei7RwEuUUphqxvICcEqJKhZtHOeUwPbGJmcJeoI2ZWTZCbpYUZ+5MHsdV1KFbQ0konksiQFdbGOkPqCvT/cDfs2n6s+ch5B+JFyGAZAgMBAAECggEAV57YLp8IC7WD/tBxuGEDDE9v0qfsouhWUs0DTHX4JDB86wWNciH0fbRe6+4/ZnQlwVpvrLFiW/lHVMe+4MIfS2/xwuXnCd1QvsbZ3tN1FpdqcOSaANB+NAqbmIm+RzBnWtyrs63rCv21eC+qPSK3STNRIEhH7gP9e5P8QQKBtTm/L9WE0EkRv5tumW3zGQqq+pq00LivmcvhXDm6QvyoMgIsQoxeKdDJ5+yCscxv1hBfvoL1cd35PzW3E9uICt6g3P/tT1xsVYuUDekLMbvRU4VPRerwL44mogCIJsmg1kBJWwZflrV2NnLtFrwtjXvMk8ZXfwKLoY/lUOxU3UZikQKBgQC/b5hES18dWVOEn3/Fx94PvQAK15UWm7fXYOmoyGEONydGVmPjiZKApvJrO/lqZqfl8bhy0cEVmoQofr2cUrJ3R2TuZIOKiZkg7Pegsu7BoGqBAJNag+iPlEpwu0THINltdgwMs9h+8L+cjixbJjgP2qG0m8pd6fxt52CrYELDnQKBgQC1MP75dxl3qy2foQYR1o6lRz0/64xZjTdjBMjVyMIOhmfUZwyKjRWykAcZNDhW81myYSplYKUin2TPxl5RHB3I/Zig8znpiij580qtpGl7CnqYkMV8+W5iRHRDdWlnXb4f362GXy2D+stZLaOVaKvhJ1N3rj4cKICNjSe55Fk7rQKBgHc2m3AML9MrCWORoBQefx7158zYq7NEjZvGcjv1bNtZZU/cBKBxz5XmYRh+ZLfp7ay4dtCp5r/5VUuSgamTpie5ghUi6vee8IkciKi+RQi3SRvEq/62HmErS6AgPphy0HPmC2LtrGiArBJmRyEMD+VvlTvPuJn7WINojz6p12nRAoGAPx2jI+kd4Paq/NkNkTcpF1+6cUKu8B7l9UMcZoP5PTAKiQ2ga777mOjc4CW1nmxEiYOZThkdTPMzHcFe52gg4/uaqC4xtS1gWrkqAVStPaQH0o9Ti9YjYm2wBjOnFM+tw9KZ0p3i7/9zyEvCmPAON28Ifz8d+ZcOOMC73uAxST0CgYEAigKmR7U+pPV+noey0t6nfCb3cYjE8O+2eoSkCwgDgl+3ghVTKQvtfugWWKiOqOF53KxUrTCKAcy8b0WJMXn1/Rq1pf1Xml97BKs2hvVFSCnOYk5jvy4WaXs49Dd233PiqDbPz1ZblSfISPPip5N4JtFpU2MtJSd9pO/Ti4+wDPM=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAofiI7Aaj/CvEp+C/qR3ck//f1PcP2BofL8D4Zhe9n/K64NlNSNROatuu7vXCI69IPvEbzrDk3M7bIJMc+1m/GOiG57Mb7oNPI6TtV09BgyGfbfvwV4ZFGxgVvnnoXfTHrFkhMDZYDU1iWdmn7mz1pOKRCTproyyR4Tiw9tGkXJMHs+xRk3gfRQLjTBnblCQQ09glug7jhsJxWf28JL2dmKexUtN07uOuOfCLYNUVUB7Q5dUWPCC8kHLqr/ZsAOH5ZUnkBVZdzZTTLiS0IDdZMKvaeUBykGTXHauwnfR4NtkCLgNKxrZwJODXZkrWsuPDiu8TJJc2/Rg1hGPRpNdGQwIDAQAB
  gatewayUrl: https://openapi.alipay.com/gateway.do
  sysServiceProviderId: 1234
  notifyUrl: https://edu.qw1000.cn/pay/student/alipayNotify
wx:
  pay:
    #微信公众号或者小程序等的appid
    appId: wxad0415da8ceb2d10
    #微信支付商户号
    mchId: 1519599551
    #微信支付商户密钥 eac16e66fe724659a74b6714c935bbc9
    mchKey: eac16e66fe724659a74b6714c935bbc9
    #subAppId: 服务商模式下的子商户公众账号ID
    #subMchId: 服务商模式下的子商户号
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）  
    keyPath: classpath:apiclient_cert.p12
    appSecret: 86f46cc7860fda13044f2b6983900f11
    notifyUrl: https://edu.qw1000.cn/pay/wx/notify/order