server:
    port: 8768
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/id_key?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: qht123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
